# Generated by Django 6.0.3 on 2026-04-25 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hearing_impairment', 'Hearing Impairment'), ('visual_impairment', 'Visual Impairment'), ('down_syndrome', 'Down Syndrome'), ('multiple_disability', 'Multiple Disability')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='learning_style',
        ),
        migrations.RemoveField(
            model_name='performancereport',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='lrn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='LRN'),
        ),
        migrations.AddField(
            model_name='student',
            name='classifications',
            field=models.ManyToManyField(blank=True, to='classroom.classification'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='YouTube/Video Link')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='task_videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='task_outputs/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='classroom.student')),
            ],
        ),
        migrations.DeleteModel(
            name='TeachingStrategy',
        ),
        migrations.DeleteModel(
            name='LearningStyle',
        ),
        migrations.DeleteModel(
            name='PerformanceReport',
        ),
    ]
