# Generated by Django 6.0.3 on 2026-05-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_classification_remove_student_learning_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grading_type',
            field=models.CharField(choices=[('graded', 'Graded'), ('ungraded', 'Ungraded')], default='ungraded', help_text='SPED learners are typically ungraded', max_length=20),
        ),
    ]
