# Generated by Django 6.0.3 on 2026-05-02 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_student_grading_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='learning_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='learning_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('developing', 'Developing'), ('independent', 'Independent')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_academic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_motor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_selfcare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_social',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('achieved', 'Achieved')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='skills_focus',
            field=models.CharField(blank=True, help_text='Comma-separated e.g. Communication, Motor Skills', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='classroom.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
