# Generated by Django 6.0.3 on 2026-05-06 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_userprofile_is_online_userprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enjoyment', models.IntegerField(blank=True, choices=[(1, 'Did not enjoy'), (2, 'Okay'), (3, 'Liked it'), (4, 'Really liked it'), (5, 'Loved it')], null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('little', 'A little hard'), ('very_hard', 'Very hard')], max_length=20)),
                ('effort', models.CharField(blank=True, choices=[('alone', 'I did it by myself'), ('some_help', 'I needed some help'), ('lot_help', 'I needed a lot of help')], max_length=20)),
                ('feeling', models.CharField(blank=True, choices=[('happy', 'Happy'), ('okay', 'Okay'), ('frustrated', 'Frustrated')], max_length=20)),
                ('participation', models.CharField(blank=True, choices=[('active', 'Active'), ('okay', 'Okay'), ('encouraged', 'Needed encouragement')], max_length=20)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='classroom.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
