# Generated by Django 6.0.3 on 2026-05-06 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_students(apps, schema_editor):
    UserProfile = apps.get_model('classroom', 'UserProfile')
    Student = apps.get_model('classroom', 'Student')

    teacher_profile = (
        UserProfile.objects
        .filter(role='teacher')
        .select_related('user')
        .order_by('user__date_joined', 'user__username')
        .first()
    )
    if teacher_profile:
        Student.objects.filter(assigned_teacher__isnull=True).update(assigned_teacher=teacher_profile.user)


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_taskevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_existing_students, migrations.RunPython.noop),
    ]
