# Generated by Django 6.0.3 on 2026-05-07 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_student_assigned_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('achieved', 'Achieved'), ('improving', 'Improving'), ('in_progress', 'In Progress'), ('needs_support', 'Needs Support')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(default='#808080', help_text='Hex color code for UI (e.g., #28a745 for green)', max_length=7)),
                ('emoji', models.CharField(blank=True, help_text='Emoji representation', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['label_type'],
            },
        ),
        migrations.CreateModel(
            name='SPEDSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='skills', help_text='Category for organization (e.g., communication, motor, social, selfcare)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndividualLearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField(blank=True, help_text="Student's learning strengths and abilities")),
                ('challenges', models.TextField(blank=True, help_text='Learning challenges and areas needing support')),
                ('short_term_goals', models.TextField(blank=True, help_text='Goals for the next 1-3 months')),
                ('long_term_goals', models.TextField(blank=True, help_text='Goals for the semester/year')),
                ('accommodations', models.TextField(blank=True, help_text='Classroom accommodations (e.g., extra time, visual aids)')),
                ('learning_strategies', models.TextField(blank=True, help_text='Recommended teaching strategies')),
                ('parent_involvement', models.TextField(blank=True, help_text='Ways parents can support learning at home')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('last_reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilp_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plan', to='classroom.student')),
            ],
            options={
                'verbose_name': 'Individual Learning Plan',
                'verbose_name_plural': 'Individual Learning Plans',
            },
        ),
        migrations.CreateModel(
            name='ProgressAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(help_text='Type of achievement (e.g., Completed Daily Routine, Participated in Group Activity)', max_length=100)),
                ('description', models.TextField()),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='classroom.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='classroom.spedsubject')),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, help_text="Teacher's observation of learner's progress")),
                ('tasks_completed', models.TextField(blank=True, help_text='Comma-separated list of tasks completed')),
                ('attendance_participation', models.CharField(blank=True, help_text='Notes on attendance and participation', max_length=200)),
                ('week_starting', models.DateField(help_text='Start date of the week being tracked')),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_logs', to='classroom.progresslabel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='classroom.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_logs_recorded', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='classroom.spedsubject')),
            ],
            options={
                'ordering': ['-week_starting'],
                'unique_together': {('student', 'subject', 'week_starting')},
            },
        ),
    ]
