# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_subject_task_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='task_recordings/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_recordings', to='classroom.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_recordings', to='classroom.subject')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='classroom.task')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
